-- Complete idempotent SQL seed for PostgreSQL
-- Creates tables (if missing) and inserts sample data. Safe to run multiple times.

BEGIN;

-- Roles
CREATE TABLE IF NOT EXISTS roles (
	role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	role_name VARCHAR(200) NOT NULL UNIQUE,
	role_code VARCHAR(100) NOT NULL UNIQUE,
	role_description TEXT
);

-- Sports
CREATE TABLE IF NOT EXISTS sports (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	sport_name VARCHAR(200) NOT NULL UNIQUE,
	description TEXT
);

-- Categories (self-referencing)
CREATE TABLE IF NOT EXISTS categories (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	category_name VARCHAR(200) NOT NULL UNIQUE,
	description TEXT,
	parent_id BIGINT REFERENCES categories(id) ON DELETE SET NULL
);

-- Brands
CREATE TABLE IF NOT EXISTS brands (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	brand_name VARCHAR(200),
	slug VARCHAR(200) NOT NULL UNIQUE,
	banner VARCHAR(1000),
	logo VARCHAR(1000),
	description TEXT,
	is_active BOOLEAN DEFAULT TRUE NOT NULL,
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now()
);

-- Products
CREATE TABLE IF NOT EXISTS products (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	product_name VARCHAR(500) NOT NULL,
	description TEXT,
	category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
	brand_id BIGINT REFERENCES brands(id) ON DELETE SET NULL,
	sport_id BIGINT REFERENCES sports(id) ON DELETE SET NULL
);

-- Product variants
CREATE TABLE IF NOT EXISTS product_variants (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	sku VARCHAR(200),
	color VARCHAR(100),
	size VARCHAR(100),
	price NUMERIC(12,2),
	stock_quantity INTEGER,
	product_id BIGINT REFERENCES products(id) ON DELETE CASCADE
);

-- Users
CREATE TABLE IF NOT EXISTS users (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	full_name VARCHAR(300) NOT NULL,
	email VARCHAR(320) NOT NULL UNIQUE,
	phone_number VARCHAR(50) NOT NULL UNIQUE,
	status BOOLEAN NOT NULL DEFAULT TRUE,
	password VARCHAR(1000) NOT NULL,
	failed_login_attempts INTEGER DEFAULT 0,
	lock_time TIMESTAMP WITHOUT TIME ZONE,
	last_password_change_date TIMESTAMP WITHOUT TIME ZONE,
	last_login_date TIMESTAMP WITHOUT TIME ZONE,
	role_id BIGINT REFERENCES roles(role_id) ON DELETE SET NULL,
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now()
);

-- User addresses
CREATE TABLE IF NOT EXISTS user_addresses (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	recipient_name VARCHAR(300) NOT NULL,
	phone_number VARCHAR(50) NOT NULL,
	city VARCHAR(200) NOT NULL,
	district VARCHAR(200) NOT NULL,
	ward VARCHAR(200) NOT NULL,
	street VARCHAR(500) NOT NULL,
	is_default BOOLEAN DEFAULT FALSE,
	user_id BIGINT REFERENCES users(id) ON DELETE CASCADE
);

-- Seed data: roles (use the rows you provided)
INSERT INTO roles (role_code, role_name, role_description)
VALUES
	('ADMIN',   'Quản Trị Viên',   'Toàn quyền quản lý hệ thống'),
	('SHIPPER', 'Người giao hàng', 'Giao hàng và thay đổi trạng thái đơn hàng'),
	('MEMBER',  'Thành Viên',      'Người dùng thông thường')
ON CONFLICT (role_code) DO NOTHING;

-- Seed sports
INSERT INTO sports (sport_name, description)
VALUES
	('Football', 'Bóng đá'),
	('Basketball', 'Bóng rổ'),
	('General', 'Chung')
ON CONFLICT (sport_name) DO NOTHING;

-- Seed categories
INSERT INTO categories (category_name, description)
VALUES
	('Shoes', 'Giày thể thao'),
	('Apparel', 'Quần áo thể thao')
ON CONFLICT (category_name) DO NOTHING;

-- Seed brands
INSERT INTO brands (brand_name, slug, banner, logo, description)
VALUES
	('Brand A', 'brand-a', '', '', 'Hãng thử nghiệm A'),
	('Brand B', 'brand-b', '', '', 'Hãng thử nghiệm B')
ON CONFLICT (slug) DO NOTHING;

-- Seed products (linking to existing category/brand/sport by name/slug)
-- Product 1
INSERT INTO products (product_name, description, category_id, brand_id, sport_id)
VALUES (
	'Running Shoe X',
	'Giày chạy bộ nhẹ và êm',
	(SELECT id FROM categories WHERE category_name = 'Shoes' LIMIT 1),
	(SELECT id FROM brands WHERE slug = 'brand-a' LIMIT 1),
	(SELECT id FROM sports WHERE sport_name = 'General' LIMIT 1)
)
ON CONFLICT DO NOTHING;

-- Product 2
INSERT INTO products (product_name, description, category_id, brand_id, sport_id)
VALUES (
	'Training Tee',
	'Áo tập đa năng',
	(SELECT id FROM categories WHERE category_name = 'Apparel' LIMIT 1),
	(SELECT id FROM brands WHERE slug = 'brand-b' LIMIT 1),
	(SELECT id FROM sports WHERE sport_name = 'General' LIMIT 1)
)
ON CONFLICT DO NOTHING;

-- Seed product variants (one variant per product)
INSERT INTO product_variants (sku, color, size, price, stock_quantity, product_id)
VALUES
	('SKU-RUNX-001','Black','42',79.99,100,(SELECT id FROM products WHERE product_name = 'Running Shoe X' LIMIT 1)),
	('SKU-TEE-001','White','M',19.99,200,(SELECT id FROM products WHERE product_name = 'Training Tee' LIMIT 1))
ON CONFLICT DO NOTHING;

-- Seed an admin user (role_id resolved at insert time)
-- NOTE: update the password value to a proper hash in production.
INSERT INTO users (full_name, email, phone_number, status, password, role_id)
VALUES (
	'Admin User',
	'admin@example.com',
	'0123456789',
	TRUE,
	'$2y$10$change_this_to_a_real_hash',
	(SELECT role_id FROM roles WHERE role_code = 'ADMIN' LIMIT 1)
)
ON CONFLICT (email) DO NOTHING;

-- Seed a sample member user
INSERT INTO users (full_name, email, phone_number, status, password, role_id)
VALUES (
	'Member User',
	'member@example.com',
	'0987654321',
	TRUE,
	'$2y$10$change_this_to_a_real_hash',
	(SELECT role_id FROM roles WHERE role_code = 'MEMBER' LIMIT 1)
)
ON CONFLICT (email) DO NOTHING;

-- Seed addresses for member user
INSERT INTO user_addresses (recipient_name, phone_number, city, district, ward, street, is_default, user_id)
VALUES (
	'Member User', '0987654321', 'Hanoi', 'Ba Dinh', 'Phuc Xa', '123 Example St', TRUE,
	(SELECT id FROM users WHERE email = 'member@example.com' LIMIT 1)
)
ON CONFLICT DO NOTHING;

COMMIT;

